### ISSUE TITLE
why do not support for x84_64-unknown-linux-musl?

### ISSUE THREAD

**Issue by reison1218** [lemunozm/message-io#101]
i really like this crate,it's easy to understand and use,but why do not support for x84_64-unknown-linux-musl?
i mean,the cross compile for compile x84_64-unknown-linux-musl is easy than x84_64-unknown-linux-gnu right?
i can not find a good way to easy cross compile to x84_64-unknown-linux-gnu.
if u know,could u pls tell me?oh,by the way,i am coding on mac.

**Comment by lemunozm** [comment]
Hi @reison1218, I'm glad you find message-io easy to use. It's one of the main motivations :)

What do you mean with *"not support for `x84_64-unknown-linux-musl`"*? It should compile. If you get an OpenSSL error it's due because you need to point to the correct OpenSSL for the target you are cross-compiling. OpenSSL is used only by WebSocket, if you don't use Websocket you can avoid compiling it using:
```sh
cargo build --target x86_64-unknown-linux-musl --no-default-features --features "tcp udp"
```

Is this your problem?

**Comment by reison1218** [comment]
oh,as u say!it's work,thank u
base on it,i can try more this crate now.thanks for your job!
