### ISSUE TITLE
Specify network interface

### ISSUE THREAD

**Issue by pmirabel** [lemunozm/message-io#118]
Hello,
Is there any way to specify which network interface to use (linux user)?
I want message-io to communicate over wired connection, but it uses radio by default.
I cannot find any mention to it... Is it "embedded" in _mio_?
thanks!

**Comment by lemunozm** [comment]
Hi @pmirabel

If you want to listen from a network interface as a server, the local IP you choose for listening corresponds to that interface. If you want to specify it when you connect to a remote server, currently is not supported. It's a rare use-case since the OS will usually determine the interface used. In fact, the own [std::net::TcpStream](https://doc.rust-lang.org/std/net/struct.TcpStream.html) do not allow configure this. I think (but not sure) you can get the correct interface, at the OS level, configuring which IPs are addressable for each interface.

Anyway, other rust TCP crates (as socket2 crate, already used by message-io) allow binding a TCP socket to an interface when it is connected, so, if your use-case is necessary, I think it could be added to message-io as a new function, `connect_by(origin, dest)` for example, although it will modified the internal adapter API to allow this configuration.

**Comment by pmirabel** [comment]
Thanks,
I forgot some context, sorry about that.

My issue is that I am using UDP multicast eg. `node.network().listen(Transport::Udp, MULTICAST_ADDR)` where  `static MULTICAST_ADDR: &str = "239.200.200.200:9977";`
By now, the wired interface is configured to use `192.169.1.X` IP adresses (and a DHCP server allow other peers to get whatever they need to join the network).

Does your answer still apply?

**Comment by lemunozm** [comment]
Ohh, ok. The answer is slightly different. Listening by multicast required two addresses, one, the interface you want to listen to, and the other one, the multicast IP group from which you want to listen to messages.

Since `message-io` tries to generalize and be transport agnostic, and only receive one IP address to listen to. I need to make some assumptions because I have 2 addresses but 1 address parameter in the `listen()`. So the interface chosen is hardcoded to `0.0.0.0` (the default interface), and this is the issue you're experimenting.

I will think about it (ideas are welcome!) of how to allow specify the interface along with the multicast IP in the same listen to call without knowledge of the underlying transport. Maybe the `listen()` parameter could be a `TransportConfiguration` trait, that each adapter should be implement, and UDP gives you a configuration for Multicast.

**Comment by lemunozm** [comment]
I close the issue, feel free to reopen it if needed!
