### ISSUE TITLE
Support browser client connections (if not already?)

### ISSUE THREAD

**Issue by lokimckay** [lemunozm/message-io#122]
Hello, I read through the docs but am still unsure if my use case is supported

I'm trying to connect to a `message-io` websocket server from a Chrome extension (i.e. the standard browser [Websocket object](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket))

## Reproduction steps
1. Setup a minimal example of `message-io` according to the [readme example](https://github.com/lemunozm/message-io#all-in-one-tcp-udp-and-websocket-echo-server)
2. Remove TCP and UDP transports from the example
3. Configure `message-io` to listen at `127.0.0.1:<port>`
4. Install [this chrome extension](https://chrome.google.com/webstore/detail/simple-websocket-client/pfdhoblngboilpfeibdedpjgfnlcodoo?hl=en#:~:text=Simple%20WebSocket%20Client%20is%20an,for%20your%20Web%20Socket%20server.) ([source here](https://github.com/hakobera/Simple-WebSocket-Client))
5. Open the extension page
6. Connect to `127.0.0.1:<port>` in the URL field
7. Note that "`Client connected`" is correctly reported by `message-io` in rust terminal
8. Send a test message via the Request field

## Expected outcome

- `Received: <message>` should be logged in the rust terminal
- The `message-io` server should ping-pong the test message back to the chrome extension
- The response message should be shown in black in the Message Log field

![image](https://user-images.githubusercontent.com/14341953/161093991-97d9627d-4786-40e9-abf0-ead75076e46e.png)

## Actual outcome

- No messages are logged in the rust terminal
- Test message is shown in red (indicates that it was requested by client)
- No response message (black) is shown

![image](https://user-images.githubusercontent.com/14341953/161093928-823c52fc-e4e0-448a-8074-2bcb8f55e0b3.png)

Why is no response being sent back?

**Comment by lemunozm** [comment]
Hi @lokimckay,

First of all, thanks for your great explanation and reproduction steps 😃 

WebSocket can support two kinds of message data formats: binary and text. Since `message-io` handle the input/output data as binary, the WS adaptor used is only implemented for binary mode. The extension you're using sends data to the server in text mode, and `message-io` drops the message.

I tested allowing message-io to understand the Text message, but because the WS adaptor always sends in binary mode, the extension, in this case, is who drops the binary message.

I hope your real case can support binary messages. Adding the **text** format support to message-io could be possible, but there is some decision points as "how to send a WS message specifying the format in a generic `send()` of the `message-io` interface" that must be evaluated before.

**Comment by lokimckay** [comment]
Thanks for the great project and explanation @lemunozm 😄 

Do you know if it is possible for the [browser implementation of Websocket](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/WebSocket) to send as binary data? (as you say is required?) I find it hard to determine this from their docs

I created a minimal reproduction repo using a simple `index.html` file and Javascript instead of the third-party chrome extension - but I still see the same behaviour that I reported in my issue

Can you tell me if I am still trying to send the messages as text?

https://github.com/lokimckay-references/message-io-122

**Comment by lokimckay** [comment]
Woops, answered my own question 🤦 
I didn't understand that the javascript was literally sending a `string` to the Rust websocket, and it needed to instead send a byte array

I have updated my reference repo at this commit: https://github.com/lokimckay-references/message-io-122/commit/10897f7a48ef7d44395dc32a42be375d2827354f

Behaves as expected 🎉 
![image](https://user-images.githubusercontent.com/14341953/161531779-90118e71-37b3-403f-a244-440f5ed148b6.png)

Will close the issue now, thanks for your help 😄
