### ISSUE TITLE
Scaling of a application

### ISSUE THREAD

**Issue by daxartio** [lemunozm/message-io#165]
Hello!

How can i scale a application which uses the library? I would to connect 2 or more persons to one room and i hope they are routed to one instance of application. Else they cannot to text each other

**Comment by lemunozm** [comment]
Hi!

Could you expand on what you mean by scaling the application or give a bit more context? `message-io` supports multiple connections/listeners

**Comment by daxartio** [comment]
Of course.

I mean that i want to launch a few instances of application in k8s.

**Comment by lemunozm** [comment]
I think this problem is out of the scope of `message-io`.

In the same way, you would solve this problem using any other library, you can apply for it.
Suppose you have a typical http server and you launch several instances in k8s, how do you share data between those instances? The same solution you use there you can use in `message-io`. i.e. a central coordination instance or sharing the same database among those instances

**Comment by daxartio** [comment]
Ok, thanks

I thought there is a right way to route traffic between instances.

Maybe i need to use another library for that. More likely it will be consistent hashing by a room_id or another key
<img width="790" alt="image" src="https://github.com/lemunozm/message-io/assets/11211587/712a2359-4f2a-4cc4-89fd-e305bc280488">

**Comment by lemunozm** [comment]
Maybe you can create connections between each instance, let each instance know the other, and pass the `User3` info to `User1`, for example. From `Instance1` perspective, `Instance2` would be like "another" user.

**Comment by lemunozm** [comment]
Although the above would not imply "scaling" as it is. I think the best way is to redirect users belonging to the same room to the same instance.
