### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by sigmaSd** [lemunozm/message-io#2]
This is especially important since this crate is meant to be used as a library.

For a example an nmap scan while termchat is active will crash here https://github.com/lemunozm/message-io/blob/master/src/network_adapter.rs#L348

**Comment by lemunozm** [comment]
Thanks for notifying me. I will investigate the error and how to handle it.

**Comment by sigmaSd** [comment]
If you're going to investigate this specific crash, I should add that nmap by default doesn't scan high port (above 30000 maybe) , so to reproduce you can use termchat -t 20000

**Comment by lemunozm** [comment]
Thank you for the help!! This kind the error is very tricky to detect :)

**Comment by sigmaSd** [comment]
@lemunozm https://github.com/sigmaSd/message-io/tree/error_handling this branch attempts to handle all errors.

I have theses couple of notes:
- https://github.com/sigmaSd/message-io/tree/error_handling and https://github.com/sigmaSd/message-io/blob/error_handling/src/events.rs#L131 how to handle theses, can we somehow inject errors to the queue that's used by the user of the library?

- How to handle the unwraps in drop implementations, maybe its a good idea to just ignore them (let _ = )

- What do you think about https://github.com/sigmaSd/message-io/blob/error_handling/src/network_adapter.rs#L239

**Comment by sigmaSd** [comment]
I tested this branch with termchat, it caught the error where if you send a file and ctrlc the receiver it crashes and handled it pretty well.
```
Termchat: Error sending file. error: failed to send data to   
│endpoint [3]-192.168.1.9:35721 with error: Resource id '3' not exists in
│the network adapter   
```

So it was happening here https://github.com/lemunozm/message-io/blob/master/src/network_adapter.rs#L303

**Comment by sigmaSd** [comment]
Side note you can trigger a panic here https://github.com/lemunozm/message-io/blob/master/src/encoding.rs#L57 substract with overflow like this:
- open termchat -t 20000
- nc localhost 2000
- write the following lines in nc 
```
    a
    aa
    aaa
```

**Comment by lemunozm** [comment]
Hi, @sigmaSd , the error handling in message-io has a lot of tricky parts. I had some ideas in mind that I want to develop.

I would distinguish 2 types of errors:
- Errors that the user must be able to react to this in case they happen. For example, currently, reset-by-peer error gets panic and it should not, a deserialization error panics too and the user could want to react to this and be protected from malformed messages.
- Errors that the user should not react to this. For example, a serialization error, when the sender sends a new event in the queue, or the drop internal threads that you have commented. Why no? Because they are errors that happen because the user is used the bad in a wrong way. In case of the `send` method of `EventSender` it will panics if the `EventQueue` has been dropped (something similar with the `receive` method). This is a wrong API usage, because the `EventQueue` should be alive, and the user should not react to this error because it never mush happens in production. It's true, that use unwrap is not probably the best idea, because the user does not know what could be happening, but I think that an `except` with a good explanation of what the user is doing bad is enough. Another way to target this is making the lifetime of the sender less than the `EventQueue`, but maybe this makes difficult the API usage. I want to study this.

Regarding the first type of error, I have the idea in mind to dispatch a `NetEvent::RemovedEndpoint(endpoint, <reason>)` where reason could be `DeseriaziliationProblem` `Disconnection` `Reset`? and thinks like that.

I think that my explanation maybe answers some of your notes. 

Regarding:

> What do you think about https://github.com/sigmaSd/message-io/blob/error_handling/src/network_adapter.rs#L239

I think that is probably an issue that could imply architectural changes in the future (maybe add a writing buffer for each `send` if not all data have been sent? wake up at POLL_IN events in the poll method to send the missing data later?). I never got a scenario when this happens. Maybe because I need some network saturation to get it fails.

I keep in mind to test the scenario you telling me :) Thanks for your analysis!

**Comment by lemunozm** [comment]
Regarding the NetEvent modifications, I leave here a sketch:
https://github.com/lemunozm/message-io/tree/error_handling

**Comment by lemunozm** [comment]
https://github.com/lemunozm/message-io/pull/10 fixes the `termchat` crash by reset-by-peer error

**Comment by sigmaSd** [comment]
The netcat panic I mentioned above still happens though, not sure if you want to handle that.

**Comment by lemunozm** [comment]
Did you test with a `termchat` that uses `message-io` version 0.5?

**Comment by sigmaSd** [comment]
Yes with the git version of message io

**Comment by lemunozm** [comment]
I can confirm that running a `termchat` instance (master branch) and run `nmap -p 1-65535 localhost` do not breaks the termchat (at least on the same computer). Are you using any additional option to `nmap`?

**Comment by sigmaSd** [comment]
The nmap issue is resolved.

Im talking about netcat(nc).
I posted above the input that causes termchat to panic.

**Comment by lemunozm** [comment]
Sorry @sigmaSd, I misunderstand you. You are right, the crash continues happening.

**Comment by lemunozm** [comment]
Now it works, thanks @sigmaSd !
